### ISSUE TITLE
Seems to have been patched by both Chrome and Firefox. No selectors that can select input fields of type 'password' on the basis of their values of their contents

### ISSUE THREAD

**Issue by ghost** [maxchehab/CSS-Keylogging#3]

**Comment by maxchehab** [comment]
Where is evidence of this?

**Comment by anusaini** [comment]
@thehumanmeshnet Just checked on instagram, works!

**Comment by johnnymatthews** [comment]
Can confirm it's still working on the latest stable build from Chrome (64.0.3282.167-1). Although it does have issues collecting all the characters, and sometimes not in the correct order.

![yarn](https://user-images.githubusercontent.com/9611008/36475647-3e21aab6-16f3-11e8-978d-91ce72787275.png)

**Comment by arjunmayilvaganan** [comment]
@mohnjatthews 
From other issues on this repo:
1. Url responses are being cached. So, no requests are being fired for a character repeat.
2. Asynchronous.

**Comment by bramus** [comment]
Same findings here: browsers are clever enough to prevent this should a rogue piece of CSS be injected. Jotted down my findings on https://www.bram.us/2018/02/21/css-keylogger-and-why-you-shouldnt-worry-about-it/

**Comment by kapouer** [comment]
@bramus these are all bugs that should be addressed by these browsers. The CSS keylogger must live !

**Comment by grssam** [comment]
URL response caching can be prevented by setting correct no-cache response headers.

Another problem I see in theory - CSS background-image property would not be re-applied in case the last character remains the same. i.e. if there are any consecutive repeated characters in the password, they would be logged only once.
That's in theory. Haven't tried the logger yet, if someone could confirm otherwise, I would be interested to see why that happens.

**Comment by nunks** [comment]
I don't get it, why the chrome extension? I made a plain HTML containing all the ASCII ending selectors and a password input field, and typing into the input doesn't trigger any background changes. It works if I change the field's *value* attribute by hand or JS, though.

**Comment by kapouer** [comment]
That chrome extension installing just a CSS file cannot possibly be malign right ?

**Comment by nunks** [comment]
Hahaha, yeah, I meant I don't get what makes this keylogger work and assume it is something inside the extension. Typing into a password input doesn't change it's value attribute, thus not triggering the CSS selectors...

**Comment by nunks** [comment]
Ah, I think I understand now: the password field on Instagram's login form has its *value* attribute dynamically changed when I type into it. Ugh... The vulnerability here then is not CSS's fault, it's the app's fault for capturing what the user is typing and storing the string into an HTML attribute. Google seems to do it too, storing it in a *data-* attribute... That's why you need an extension to inject the malicious CSS into those vulnerable login pages.
Sorry if I'm stating the obivous, just "thinking aloud" in a comment box... :grimacing:
